*Tonel-GemStone-Tests
creatClassDefinition: nameString superclassName: superclassString category: categoryString instVarNames: ivarArray classVarNames: cvarArray poolDictionaryNames: poolArray classInstVarNames: civarArray type: typeSymbol comment: commentString

  ^ MCClassDefinition
    name: nameString
    superclassName: superclassString
    traitComposition: '{}'
    classTraitComposition: '{}'
    category: categoryString
    instVarNames: ivarArray
    classVarNames: cvarArray
    poolDictionaryNames: poolArray
    classInstVarNames: civarArray
    type: typeSymbol
    comment: commentString
    commentStamp: nil